// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InventoryBalancePublicSchema = {
    properties: {
        processing_unit_id: {
            type: 'string',
            format: 'uuid',
            title: 'Processing Unit Id'
        },
        item_name: {
            type: 'string',
            title: 'Item Name'
        },
        item_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Code'
        },
        wool_content: {
            type: 'string',
            title: 'Wool Content'
        },
        color_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Code'
        },
        dye_lot_no: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dye Lot No'
        },
        rolls_balance: {
            type: 'integer',
            title: 'Rolls Balance'
        },
        meters_balance: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Meters Balance'
        }
    },
    type: 'object',
    required: ['processing_unit_id', 'item_name', 'wool_content', 'rolls_balance', 'meters_balance'],
    title: 'InventoryBalancePublic'
} as const;

export const InventoryBalancesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InventoryBalancePublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'InventoryBalancesPublic'
} as const;

export const InventoryDocumentCreateSchema = {
    properties: {
        document_type: {
            '$ref': '#/components/schemas/InventoryDocumentType'
        },
        business_date: {
            type: 'string',
            format: 'date',
            title: 'Business Date'
        },
        processing_unit_id: {
            type: 'string',
            format: 'uuid',
            title: 'Processing Unit Id'
        },
        receiving_unit_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Receiving Unit Id'
        },
        document_number: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Document Number'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        lines: {
            items: {
                '$ref': '#/components/schemas/InventoryLineCreate'
            },
            type: 'array',
            minItems: 1,
            title: 'Lines'
        }
    },
    type: 'object',
    required: ['document_type', 'business_date', 'processing_unit_id', 'document_number', 'lines'],
    title: 'InventoryDocumentCreate'
} as const;

export const InventoryDocumentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        document_type: {
            '$ref': '#/components/schemas/InventoryDocumentType'
        },
        business_date: {
            type: 'string',
            format: 'date',
            title: 'Business Date'
        },
        processing_unit_id: {
            type: 'string',
            format: 'uuid',
            title: 'Processing Unit Id'
        },
        receiving_unit_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Receiving Unit Id'
        },
        document_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Number'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        lines: {
            items: {
                '$ref': '#/components/schemas/InventoryLinePublic'
            },
            type: 'array',
            title: 'Lines'
        }
    },
    type: 'object',
    required: ['id', 'document_type', 'business_date', 'processing_unit_id', 'receiving_unit_id', 'document_number', 'remarks', 'deleted_at', 'lines'],
    title: 'InventoryDocumentPublic'
} as const;

export const InventoryDocumentTypeSchema = {
    type: 'string',
    enum: ['RAW_RECEIPT', 'RAW_RETURN', 'FINISHED_SHIPMENT', 'FINISHED_RECEIPT'],
    title: 'InventoryDocumentType'
} as const;

export const InventoryDocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InventoryDocumentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InventoryDocumentsPublic'
} as const;

export const InventoryLedgerEntriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InventoryLedgerEntryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InventoryLedgerEntriesPublic'
} as const;

export const InventoryLedgerEntryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ledger_kind: {
            type: 'string',
            title: 'Ledger Kind'
        },
        movement_type: {
            type: 'string',
            title: 'Movement Type'
        },
        business_date: {
            type: 'string',
            format: 'date',
            title: 'Business Date'
        },
        processing_unit_id: {
            type: 'string',
            format: 'uuid',
            title: 'Processing Unit Id'
        },
        document_line_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Line Id'
        },
        item_name: {
            type: 'string',
            title: 'Item Name'
        },
        item_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Code'
        },
        wool_content: {
            type: 'string',
            title: 'Wool Content'
        },
        color_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Code'
        },
        dye_lot_no: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dye Lot No'
        },
        rolls_delta: {
            type: 'integer',
            title: 'Rolls Delta'
        },
        meters_delta: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Meters Delta'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['id', 'ledger_kind', 'movement_type', 'business_date', 'processing_unit_id', 'document_line_id', 'item_name', 'item_code', 'wool_content', 'color_code', 'dye_lot_no', 'rolls_delta', 'meters_delta', 'reason'],
    title: 'InventoryLedgerEntryPublic'
} as const;

export const InventoryLedgerKindSchema = {
    type: 'string',
    enum: ['RAW', 'FINISHED'],
    title: 'InventoryLedgerKind'
} as const;

export const InventoryLineCreateSchema = {
    properties: {
        item_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Item Name'
        },
        item_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Code'
        },
        wool_content: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Wool Content'
        },
        color_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Code'
        },
        dye_lot_no: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dye Lot No'
        },
        quantity_rolls: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Quantity Rolls'
        },
        quantity_meters: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quantity Meters'
        }
    },
    type: 'object',
    required: ['item_name', 'wool_content', 'quantity_rolls'],
    title: 'InventoryLineCreate'
} as const;

export const InventoryLinePublicSchema = {
    properties: {
        item_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Item Name'
        },
        item_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Code'
        },
        wool_content: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Wool Content'
        },
        color_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Code'
        },
        dye_lot_no: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dye Lot No'
        },
        quantity_rolls: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Quantity Rolls'
        },
        quantity_meters: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quantity Meters'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        line_no: {
            type: 'integer',
            title: 'Line No'
        }
    },
    type: 'object',
    required: ['item_name', 'wool_content', 'quantity_rolls', 'id', 'line_no'],
    title: 'InventoryLinePublic'
} as const;

export const InventorySuggestionsPublicSchema = {
    properties: {
        data: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'InventorySuggestionsPublic'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MasterUnitCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'MasterUnitCreate'
} as const;

export const MasterUnitPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'name', 'is_active'],
    title: 'MasterUnitPublic'
} as const;

export const MasterUnitUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'MasterUnitUpdate'
} as const;

export const MasterUnitsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MasterUnitPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MasterUnitsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RuleDocumentPublicSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['slug', 'title', 'path', 'content'],
    title: 'RuleDocumentPublic'
} as const;

export const RuleDocumentSummarySchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        path: {
            type: 'string',
            title: 'Path'
        }
    },
    type: 'object',
    required: ['slug', 'title', 'path'],
    title: 'RuleDocumentSummary'
} as const;

export const RuleDocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RuleDocumentSummary'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RuleDocumentsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;