// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const EffectivePermissionsPublicSchema = {
    properties: {
        roles: {
            items: {
                '$ref': '#/components/schemas/RoleSummary'
            },
            type: 'array',
            title: 'Roles'
        },
        permissions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Permissions'
        }
    },
    type: 'object',
    required: ['roles', 'permissions'],
    title: 'EffectivePermissionsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        },
        request_id: {
            title: 'Request Id',
            type: 'string'
        }
    },
    type: 'object',
    title: 'HTTPValidationError',
    required: ['request_id']
} as const;

export const InventoryBalancePublicSchema = {
    properties: {
        processing_unit_id: {
            type: 'string',
            format: 'uuid',
            title: 'Processing Unit Id'
        },
        item_name: {
            type: 'string',
            title: 'Item Name'
        },
        item_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Code'
        },
        wool_content: {
            type: 'string',
            title: 'Wool Content'
        },
        color_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Code'
        },
        dye_lot_no: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dye Lot No'
        },
        rolls_balance: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Rolls Balance'
        },
        meters_balance: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Meters Balance'
        }
    },
    type: 'object',
    required: ['processing_unit_id', 'item_name', 'wool_content', 'rolls_balance', 'meters_balance'],
    title: 'InventoryBalancePublic'
} as const;

export const InventoryBalancesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InventoryBalancePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InventoryBalancesPublic'
} as const;

export const InventoryDocumentCreateSchema = {
    properties: {
        document_type: {
            '$ref': '#/components/schemas/InventoryDocumentType'
        },
        business_date: {
            type: 'string',
            format: 'date',
            title: 'Business Date'
        },
        processing_unit_id: {
            type: 'string',
            format: 'uuid',
            title: 'Processing Unit Id'
        },
        receiving_unit_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Receiving Unit Id'
        },
        document_number: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Document Number'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        lines: {
            items: {
                '$ref': '#/components/schemas/InventoryLineCreate'
            },
            type: 'array',
            minItems: 1,
            title: 'Lines'
        }
    },
    type: 'object',
    required: ['document_type', 'business_date', 'processing_unit_id', 'document_number', 'lines'],
    title: 'InventoryDocumentCreate'
} as const;

export const InventoryDocumentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        document_type: {
            '$ref': '#/components/schemas/InventoryDocumentType'
        },
        business_date: {
            type: 'string',
            format: 'date',
            title: 'Business Date'
        },
        processing_unit_id: {
            type: 'string',
            format: 'uuid',
            title: 'Processing Unit Id'
        },
        receiving_unit_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Receiving Unit Id'
        },
        document_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Number'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        lines: {
            items: {
                '$ref': '#/components/schemas/InventoryLinePublic'
            },
            type: 'array',
            title: 'Lines'
        }
    },
    type: 'object',
    required: ['id', 'document_type', 'business_date', 'processing_unit_id', 'receiving_unit_id', 'document_number', 'remarks', 'deleted_at', 'lines'],
    title: 'InventoryDocumentPublic'
} as const;

export const InventoryDocumentTypeSchema = {
    type: 'string',
    enum: ['RAW_RECEIPT', 'RAW_RETURN', 'FINISHED_SHIPMENT', 'FINISHED_RECEIPT'],
    title: 'InventoryDocumentType'
} as const;

export const InventoryDocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InventoryDocumentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InventoryDocumentsPublic'
} as const;

export const InventoryLedgerEntriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InventoryLedgerEntryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InventoryLedgerEntriesPublic'
} as const;

export const InventoryLedgerEntryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ledger_kind: {
            type: 'string',
            title: 'Ledger Kind'
        },
        movement_type: {
            type: 'string',
            title: 'Movement Type'
        },
        business_date: {
            type: 'string',
            format: 'date',
            title: 'Business Date'
        },
        processing_unit_id: {
            type: 'string',
            format: 'uuid',
            title: 'Processing Unit Id'
        },
        document_line_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Line Id'
        },
        item_name: {
            type: 'string',
            title: 'Item Name'
        },
        item_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Code'
        },
        wool_content: {
            type: 'string',
            title: 'Wool Content'
        },
        color_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Code'
        },
        dye_lot_no: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dye Lot No'
        },
        rolls_delta: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Rolls Delta'
        },
        meters_delta: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Meters Delta'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['id', 'ledger_kind', 'movement_type', 'business_date', 'processing_unit_id', 'document_line_id', 'item_name', 'item_code', 'wool_content', 'color_code', 'dye_lot_no', 'rolls_delta', 'meters_delta', 'reason'],
    title: 'InventoryLedgerEntryPublic'
} as const;

export const InventoryLedgerKindSchema = {
    type: 'string',
    enum: ['RAW', 'FINISHED'],
    title: 'InventoryLedgerKind'
} as const;

export const InventoryLineCreateSchema = {
    properties: {
        item_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Item Name'
        },
        item_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Code'
        },
        wool_content: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Wool Content'
        },
        color_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Code'
        },
        dye_lot_no: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dye Lot No'
        },
        quantity_meters: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quantity Meters'
        },
        quantity_rolls: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,16}|(?=[\\d.]{1,19}0*$)\\d{0,16}\\.\\d{0,2}0*$)'
                }
            ],
            title: 'Quantity Rolls'
        }
    },
    type: 'object',
    required: ['item_name', 'wool_content', 'quantity_rolls'],
    title: 'InventoryLineCreate'
} as const;

export const InventoryLinePublicSchema = {
    properties: {
        item_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Item Name'
        },
        item_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Code'
        },
        wool_content: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Wool Content'
        },
        color_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Code'
        },
        dye_lot_no: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dye Lot No'
        },
        quantity_meters: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quantity Meters'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        line_no: {
            type: 'integer',
            title: 'Line No'
        },
        quantity_rolls: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,16}|(?=[\\d.]{1,19}0*$)\\d{0,16}\\.\\d{0,2}0*$)',
            title: 'Quantity Rolls'
        }
    },
    type: 'object',
    required: ['item_name', 'wool_content', 'id', 'line_no', 'quantity_rolls'],
    title: 'InventoryLinePublic'
} as const;

export const InventorySuggestionsPublicSchema = {
    properties: {
        data: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'InventorySuggestionsPublic'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MasterUnitCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'MasterUnitCreate'
} as const;

export const MasterUnitPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'name', 'is_active'],
    title: 'MasterUnitPublic'
} as const;

export const MasterUnitUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'MasterUnitUpdate'
} as const;

export const MasterUnitsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MasterUnitPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MasterUnitsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PermissionPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        group_name: {
            type: 'string',
            title: 'Group Name'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['id', 'code', 'group_name', 'label', 'description'],
    title: 'PermissionPublic'
} as const;

export const PermissionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PermissionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PermissionsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RoleCreateSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 64,
            minLength: 2,
            title: 'Code'
        },
        name: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        permission_codes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Permission Codes'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['code', 'name'],
    title: 'RoleCreate'
} as const;

export const RolePermissionsReplaceSchema = {
    properties: {
        permission_codes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Permission Codes'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['permission_codes'],
    title: 'RolePermissionsReplace'
} as const;

export const RolePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        is_builtin: {
            type: 'boolean',
            title: 'Is Builtin'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        permission_codes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Permission Codes'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'code', 'name', 'is_builtin', 'is_active', 'permission_codes', 'created_at', 'updated_at'],
    title: 'RolePublic'
} as const;

export const RoleSummarySchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        is_builtin: {
            type: 'boolean',
            title: 'Is Builtin'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'code', 'name', 'is_builtin', 'is_active'],
    title: 'RoleSummary'
} as const;

export const RoleUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'RoleUpdate'
} as const;

export const RolesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RolePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RolesPublic'
} as const;

export const RuleDocumentPublicSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['slug', 'title', 'path', 'content'],
    title: 'RuleDocumentPublic'
} as const;

export const RuleDocumentSummarySchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        path: {
            type: 'string',
            title: 'Path'
        }
    },
    type: 'object',
    required: ['slug', 'title', 'path'],
    title: 'RuleDocumentSummary'
} as const;

export const RuleDocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RuleDocumentSummary'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RuleDocumentsPublic'
} as const;

export const SchedulerCronPreviewPublicSchema = {
    properties: {
        base_at: {
            type: 'string',
            format: 'date-time',
            title: 'Base At'
        },
        timezone: {
            type: 'string',
            const: 'Asia/Shanghai',
            title: 'Timezone'
        },
        next_run_ats: {
            items: {
                type: 'string',
                format: 'date-time'
            },
            type: 'array',
            maxItems: 5,
            minItems: 5,
            title: 'Next Run Ats'
        }
    },
    type: 'object',
    required: ['base_at', 'timezone', 'next_run_ats'],
    title: 'SchedulerCronPreviewPublic'
} as const;

export const SchedulerJobCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Name'
        },
        class_path: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Class Path'
        },
        cron_expression: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Cron Expression'
        },
        config: {
            additionalProperties: true,
            type: 'object',
            title: 'Config'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['name', 'class_path', 'cron_expression'],
    title: 'SchedulerJobCreate'
} as const;

export const SchedulerJobPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        class_path: {
            type: 'string',
            title: 'Class Path'
        },
        cron_expression: {
            type: 'string',
            title: 'Cron Expression'
        },
        config: {
            additionalProperties: true,
            type: 'object',
            title: 'Config'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        next_run_at: {
            type: 'string',
            format: 'date-time',
            title: 'Next Run At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        updated_by: {
            type: 'string',
            format: 'uuid',
            title: 'Updated By'
        },
        can_run_now: {
            type: 'boolean',
            title: 'Can Run Now'
        },
        can_backfill: {
            type: 'boolean',
            title: 'Can Backfill'
        }
    },
    type: 'object',
    required: ['id', 'name', 'class_path', 'cron_expression', 'config', 'enabled', 'next_run_at', 'deleted_at', 'created_at', 'created_by', 'updated_at', 'updated_by', 'can_run_now', 'can_backfill'],
    title: 'SchedulerJobPublic'
} as const;

export const SchedulerJobUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        class_path: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Class Path'
        },
        cron_expression: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cron Expression'
        },
        config: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Config'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'SchedulerJobUpdate'
} as const;

export const SchedulerJobsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SchedulerJobPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SchedulerJobsPublic'
} as const;

export const SchedulerRunBackfillSchema = {
    properties: {
        planned_at: {
            type: 'string',
            format: 'date-time',
            title: 'Planned At'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['planned_at'],
    title: 'SchedulerRunBackfill'
} as const;

export const SchedulerRunPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        job_id: {
            type: 'integer',
            title: 'Job Id'
        },
        status: {
            '$ref': '#/components/schemas/SchedulerRunStatus'
        },
        trigger: {
            '$ref': '#/components/schemas/SchedulerRunTrigger'
        },
        planned_at: {
            type: 'string',
            format: 'date-time',
            title: 'Planned At'
        },
        class_path: {
            type: 'string',
            title: 'Class Path'
        },
        config: {
            additionalProperties: true,
            type: 'object',
            title: 'Config'
        },
        requested_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requested By'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        attempt_count: {
            type: 'integer',
            title: 'Attempt Count'
        },
        error_category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Category'
        },
        error_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Summary'
        }
    },
    type: 'object',
    required: ['id', 'job_id', 'status', 'trigger', 'planned_at', 'class_path', 'config', 'requested_by', 'created_at', 'started_at', 'finished_at', 'attempt_count', 'error_category', 'error_summary'],
    title: 'SchedulerRunPublic'
} as const;

export const SchedulerRunStatusSchema = {
    type: 'string',
    enum: ['QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', 'CANCELLED'],
    title: 'SchedulerRunStatus'
} as const;

export const SchedulerRunTriggerSchema = {
    type: 'string',
    enum: ['SCHEDULED', 'MANUAL_NOW', 'MANUAL_BACKFILL'],
    title: 'SchedulerRunTrigger'
} as const;

export const SchedulerRunsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SchedulerRunPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SchedulerRunsPublic'
} as const;

export const SchedulerTaskSchemaPublicSchema = {
    properties: {
        class_path: {
            type: 'string',
            title: 'Class Path'
        },
        json_schema: {
            additionalProperties: true,
            type: 'object',
            title: 'Json Schema'
        }
    },
    type: 'object',
    required: ['class_path', 'json_schema'],
    title: 'SchedulerTaskSchemaPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        role_ids: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Role Ids'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        roles: {
            items: {
                '$ref': '#/components/schemas/RoleSummary'
            },
            type: 'array',
            title: 'Roles'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRolesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RoleSummary'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'UserRolesPublic'
} as const;

export const UserRolesReplaceSchema = {
    properties: {
        role_ids: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Role Ids'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['role_ids'],
    title: 'UserRolesReplace'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;