// This file is auto-generated by @hey-api/openapi-ts

export type AiInventoryCitation = {
    source: string;
    summary: string;
};

export type AiInventoryQueryRequest = {
    question: string;
};

export type AiInventoryQueryResponse = {
    run_id: string;
    answer: string;
    citations: Array<AiInventoryCitation>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type EffectivePermissionsPublic = {
    roles: Array<RoleSummary>;
    permissions: Array<(string)>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
    request_id: string;
};

export type InventoryBalancePublic = {
    processing_unit_id: string;
    item_name: string;
    item_code?: (string | null);
    wool_content: string;
    color_code?: (string | null);
    dye_lot_no?: (string | null);
    rolls_balance: string;
    meters_balance: string;
};

export type InventoryBalancesPublic = {
    data: Array<InventoryBalancePublic>;
    count: number;
};

export type InventoryDocumentCreate = {
    document_type: InventoryDocumentType;
    business_date: string;
    processing_unit_id: string;
    receiving_unit_id?: (string | null);
    document_number: string;
    remarks?: (string | null);
    lines: Array<InventoryLineCreate>;
};

export type InventoryDocumentPublic = {
    id: string;
    document_type: InventoryDocumentType;
    business_date: string;
    processing_unit_id: string;
    receiving_unit_id: (string | null);
    document_number: (string | null);
    remarks: (string | null);
    deleted_at: (string | null);
    lines: Array<InventoryLinePublic>;
};

export type InventoryDocumentsPublic = {
    data: Array<InventoryDocumentPublic>;
    count: number;
};

export type InventoryDocumentType = 'RAW_RECEIPT' | 'RAW_RETURN' | 'FINISHED_SHIPMENT' | 'FINISHED_RECEIPT';

export type InventoryLedgerEntriesPublic = {
    data: Array<InventoryLedgerEntryPublic>;
    count: number;
};

export type InventoryLedgerEntryPublic = {
    id: string;
    ledger_kind: string;
    movement_type: string;
    business_date: string;
    processing_unit_id: string;
    document_line_id: (string | null);
    item_name: string;
    item_code: (string | null);
    wool_content: string;
    color_code: (string | null);
    dye_lot_no: (string | null);
    rolls_delta: string;
    meters_delta: string;
    reason: (string | null);
};

export type InventoryLedgerKind = 'RAW' | 'FINISHED';

export type InventoryLineCreate = {
    item_name: string;
    item_code?: (string | null);
    wool_content: string;
    color_code?: (string | null);
    dye_lot_no?: (string | null);
    quantity_meters?: (number | string | null);
    quantity_rolls: (number | string);
};

export type InventoryLinePublic = {
    item_name: string;
    item_code?: (string | null);
    wool_content: string;
    color_code?: (string | null);
    dye_lot_no?: (string | null);
    quantity_meters?: (string | null);
    id: string;
    line_no: number;
    quantity_rolls: string;
};

export type InventorySuggestionsPublic = {
    data: Array<(string)>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type MasterUnitCreate = {
    name: string;
};

export type MasterUnitPublic = {
    id: string;
    name: string;
    is_active: boolean;
};

export type MasterUnitsPublic = {
    data: Array<MasterUnitPublic>;
    count: number;
};

export type MasterUnitUpdate = {
    name?: (string | null);
    is_active?: (boolean | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PermissionPublic = {
    id: number;
    code: string;
    group_name: string;
    label: string;
    description: string;
};

export type PermissionsPublic = {
    data: Array<PermissionPublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RoleCreate = {
    code: string;
    name: string;
    description?: (string | null);
    permission_codes?: Array<(string)>;
};

export type RolePermissionsReplace = {
    permission_codes: Array<(string)>;
};

export type RolePublic = {
    id: number;
    code: string;
    name: string;
    is_builtin: boolean;
    is_active: boolean;
    description?: (string | null);
    permission_codes: Array<(string)>;
    created_at: string;
    updated_at: string;
};

export type RolesPublic = {
    data: Array<RolePublic>;
    count: number;
};

export type RoleSummary = {
    id: number;
    code: string;
    name: string;
    is_builtin: boolean;
    is_active: boolean;
};

export type RoleUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

export type RuleDocumentPublic = {
    slug: string;
    title: string;
    path: string;
    content: string;
};

export type RuleDocumentsPublic = {
    data: Array<RuleDocumentSummary>;
    count: number;
};

export type RuleDocumentSummary = {
    slug: string;
    title: string;
    path: string;
};

export type SchedulerJobCreate = {
    name: string;
    class_path: string;
    cron_expression: string;
    config?: {
        [key: string]: unknown;
    };
};

export type SchedulerJobPublic = {
    id: number;
    name: string;
    class_path: string;
    cron_expression: string;
    config: {
        [key: string]: unknown;
    };
    enabled: boolean;
    next_run_at: string;
    deleted_at: (string | null);
    created_at: string;
    created_by: string;
    updated_at: string;
    updated_by: string;
};

export type SchedulerJobsPublic = {
    data: Array<SchedulerJobPublic>;
    count: number;
};

export type SchedulerJobUpdate = {
    name?: (string | null);
    class_path?: (string | null);
    cron_expression?: (string | null);
    config?: ({
    [key: string]: unknown;
} | null);
};

export type SchedulerRunBackfill = {
    planned_at: string;
};

export type SchedulerRunPublic = {
    id: number;
    job_id: number;
    status: SchedulerRunStatus;
    trigger: SchedulerRunTrigger;
    planned_at: string;
    class_path: string;
    config: {
        [key: string]: unknown;
    };
    requested_by: (string | null);
    created_at: string;
    started_at: (string | null);
    finished_at: (string | null);
    attempt_count: number;
    error_category: (string | null);
    error_summary: (string | null);
};

export type SchedulerRunsPublic = {
    data: Array<SchedulerRunPublic>;
    count: number;
};

export type SchedulerRunStatus = 'QUEUED' | 'RUNNING' | 'SUCCEEDED' | 'FAILED' | 'SKIPPED' | 'CANCELLED';

export type SchedulerRunTrigger = 'SCHEDULED' | 'MANUAL_NOW' | 'MANUAL_BACKFILL';

export type SchedulerTaskSchemaPublic = {
    class_path: string;
    json_schema: {
        [key: string]: unknown;
    };
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    full_name?: (string | null);
    password: string;
    role_ids?: Array<(number)>;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    roles?: Array<RoleSummary>;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRolesPublic = {
    data: Array<RoleSummary>;
};

export type UserRolesReplace = {
    role_ids: Array<(number)>;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AiQueryInventoryData = {
    requestBody: AiInventoryQueryRequest;
};

export type AiQueryInventoryResponse = (AiInventoryQueryResponse);

export type DocsReadRuleDocumentsResponse = (RuleDocumentsPublic);

export type DocsReadRuleDocumentData = {
    slug: string;
};

export type DocsReadRuleDocumentResponse = (RuleDocumentPublic);

export type IamReadMyPermissionsResponse = (EffectivePermissionsPublic);

export type IamReadPermissionCatalogResponse = (PermissionsPublic);

export type IamReadRolesResponse = (RolesPublic);

export type IamCreateRoleData = {
    requestBody: RoleCreate;
};

export type IamCreateRoleResponse = (RolePublic);

export type IamUpdateRoleData = {
    requestBody: RoleUpdate;
    roleId: number;
};

export type IamUpdateRoleResponse = (RolePublic);

export type IamDeleteRoleData = {
    roleId: number;
};

export type IamDeleteRoleResponse = (Message);

export type IamReplaceRolePermissionsData = {
    requestBody: RolePermissionsReplace;
    roleId: number;
};

export type IamReplaceRolePermissionsResponse = (RolePublic);

export type IamReplaceUserRolesData = {
    requestBody: UserRolesReplace;
    userId: string;
};

export type IamReplaceUserRolesResponse = (UserRolesPublic);

export type InventoryReadProcessingUnitsData = {
    isActive?: (boolean | null);
    limit?: number;
    name?: (string | null);
    skip?: number;
};

export type InventoryReadProcessingUnitsResponse = (MasterUnitsPublic);

export type InventoryCreateProcessingUnitData = {
    requestBody: MasterUnitCreate;
};

export type InventoryCreateProcessingUnitResponse = (MasterUnitPublic);

export type InventoryUpdateProcessingUnitData = {
    requestBody: MasterUnitUpdate;
    unitId: string;
};

export type InventoryUpdateProcessingUnitResponse = (MasterUnitPublic);

export type InventoryReadReceivingUnitsData = {
    isActive?: (boolean | null);
    limit?: number;
    name?: (string | null);
    skip?: number;
};

export type InventoryReadReceivingUnitsResponse = (MasterUnitsPublic);

export type InventoryCreateReceivingUnitData = {
    requestBody: MasterUnitCreate;
};

export type InventoryCreateReceivingUnitResponse = (MasterUnitPublic);

export type InventoryUpdateReceivingUnitData = {
    requestBody: MasterUnitUpdate;
    unitId: string;
};

export type InventoryUpdateReceivingUnitResponse = (MasterUnitPublic);

export type InventoryCreateInventoryDocumentData = {
    requestBody: InventoryDocumentCreate;
};

export type InventoryCreateInventoryDocumentResponse = (InventoryDocumentPublic);

export type InventoryReadInventoryDocumentsData = {
    businessDateFrom?: (string | null);
    businessDateTo?: (string | null);
    documentNumber?: (string | null);
    documentType?: (InventoryDocumentType | null);
    includeDeleted?: boolean;
    limit?: number;
    processingUnitId?: (string | null);
    receivingUnitId?: (string | null);
    skip?: number;
};

export type InventoryReadInventoryDocumentsResponse = (InventoryDocumentsPublic);

export type InventoryReadInventoryDocumentData = {
    documentId: string;
};

export type InventoryReadInventoryDocumentResponse = (InventoryDocumentPublic);

export type InventoryUpdateInventoryDocumentData = {
    documentId: string;
    requestBody: InventoryDocumentCreate;
};

export type InventoryUpdateInventoryDocumentResponse = (InventoryDocumentPublic);

export type InventoryDeleteInventoryDocumentData = {
    documentId: string;
};

export type InventoryDeleteInventoryDocumentResponse = ({
    [key: string]: (string);
});

export type InventoryRestoreInventoryDocumentData = {
    documentId: string;
};

export type InventoryRestoreInventoryDocumentResponse = ({
    [key: string]: (string);
});

export type InventoryReadRawBalancesData = {
    itemName?: (string | null);
    limit?: number;
    processingUnitId?: (string | null);
    skip?: number;
};

export type InventoryReadRawBalancesResponse = (InventoryBalancesPublic);

export type InventoryReadFinishedBalancesData = {
    itemName?: (string | null);
    limit?: number;
    processingUnitId?: (string | null);
    skip?: number;
};

export type InventoryReadFinishedBalancesResponse = (InventoryBalancesPublic);

export type InventoryReadInventoryLedgerData = {
    colorCode?: (string | null);
    dyeLotNo?: (string | null);
    itemCode?: (string | null);
    itemName: string;
    ledgerKind: InventoryLedgerKind;
    limit?: number;
    processingUnitId: string;
    skip?: number;
    woolContent: string;
};

export type InventoryReadInventoryLedgerResponse = (InventoryLedgerEntriesPublic);

export type InventoryReadInventorySuggestionsData = {
    field: string;
    ledgerKind: InventoryLedgerKind;
    query?: (string | null);
};

export type InventoryReadInventorySuggestionsResponse = (InventorySuggestionsPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type ModulesModulesHealthCheckResponse = ({
    [key: string]: (string);
});

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SchedulerReadJobsData = {
    includeDeleted?: boolean;
    limit?: number;
    skip?: number;
};

export type SchedulerReadJobsResponse = (SchedulerJobsPublic);

export type SchedulerCreateJobData = {
    requestBody: SchedulerJobCreate;
};

export type SchedulerCreateJobResponse = (SchedulerJobPublic);

export type SchedulerReadJobData = {
    jobId: number;
};

export type SchedulerReadJobResponse = (SchedulerJobPublic);

export type SchedulerUpdateJobData = {
    jobId: number;
    requestBody: SchedulerJobUpdate;
};

export type SchedulerUpdateJobResponse = (SchedulerJobPublic);

export type SchedulerDeleteJobData = {
    jobId: number;
};

export type SchedulerDeleteJobResponse = ({
    [key: string]: (string);
});

export type SchedulerEnableJobData = {
    jobId: number;
};

export type SchedulerEnableJobResponse = (SchedulerJobPublic);

export type SchedulerDisableJobData = {
    jobId: number;
};

export type SchedulerDisableJobResponse = (SchedulerJobPublic);

export type SchedulerRestoreJobData = {
    jobId: number;
};

export type SchedulerRestoreJobResponse = (SchedulerJobPublic);

export type SchedulerRunNowData = {
    jobId: number;
};

export type SchedulerRunNowResponse = (SchedulerRunPublic);

export type SchedulerBackfillData = {
    jobId: number;
    requestBody: SchedulerRunBackfill;
};

export type SchedulerBackfillResponse = (SchedulerRunPublic);

export type SchedulerReadRunsData = {
    jobId: number;
    limit?: number;
    skip?: number;
};

export type SchedulerReadRunsResponse = (SchedulerRunsPublic);

export type SchedulerReadTaskSchemaData = {
    classPath: string;
};

export type SchedulerReadTaskSchemaResponse = (SchedulerTaskSchemaPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);