// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InventoryBalancePublic = {
    processing_unit_id: string;
    item_name: string;
    item_code?: (string | null);
    wool_content: string;
    color_code?: (string | null);
    dye_lot_no?: (string | null);
    rolls_balance: string;
    meters_balance: string;
};

export type InventoryBalancesPublic = {
    data: Array<InventoryBalancePublic>;
};

export type InventoryDocumentCreate = {
    document_type: InventoryDocumentType;
    business_date: string;
    processing_unit_id: string;
    receiving_unit_id?: (string | null);
    document_number: string;
    remarks?: (string | null);
    lines: Array<InventoryLineCreate>;
};

export type InventoryDocumentPublic = {
    id: string;
    document_type: InventoryDocumentType;
    business_date: string;
    processing_unit_id: string;
    receiving_unit_id: (string | null);
    document_number: (string | null);
    remarks: (string | null);
    deleted_at: (string | null);
    lines: Array<InventoryLinePublic>;
};

export type InventoryDocumentsPublic = {
    data: Array<InventoryDocumentPublic>;
    count: number;
};

export type InventoryDocumentType = 'RAW_RECEIPT' | 'RAW_RETURN' | 'FINISHED_SHIPMENT' | 'FINISHED_RECEIPT';

export type InventoryLedgerEntriesPublic = {
    data: Array<InventoryLedgerEntryPublic>;
    count: number;
};

export type InventoryLedgerEntryPublic = {
    id: string;
    ledger_kind: string;
    movement_type: string;
    business_date: string;
    processing_unit_id: string;
    document_line_id: (string | null);
    item_name: string;
    item_code: (string | null);
    wool_content: string;
    color_code: (string | null);
    dye_lot_no: (string | null);
    rolls_delta: string;
    meters_delta: string;
    reason: (string | null);
};

export type InventoryLedgerKind = 'RAW' | 'FINISHED';

export type InventoryLineCreate = {
    item_name: string;
    item_code?: (string | null);
    wool_content: string;
    color_code?: (string | null);
    dye_lot_no?: (string | null);
    quantity_meters?: (number | string | null);
    quantity_rolls: (number | string);
};

export type InventoryLinePublic = {
    item_name: string;
    item_code?: (string | null);
    wool_content: string;
    color_code?: (string | null);
    dye_lot_no?: (string | null);
    quantity_meters?: (string | null);
    id: string;
    line_no: number;
    quantity_rolls: string;
};

export type InventorySuggestionsPublic = {
    data: Array<(string)>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type MasterUnitCreate = {
    name: string;
};

export type MasterUnitPublic = {
    id: string;
    name: string;
    is_active: boolean;
};

export type MasterUnitsPublic = {
    data: Array<MasterUnitPublic>;
    count: number;
};

export type MasterUnitUpdate = {
    name?: (string | null);
    is_active?: (boolean | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RuleDocumentPublic = {
    slug: string;
    title: string;
    path: string;
    content: string;
};

export type RuleDocumentsPublic = {
    data: Array<RuleDocumentSummary>;
    count: number;
};

export type RuleDocumentSummary = {
    slug: string;
    title: string;
    path: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type DocsReadRuleDocumentsResponse = (RuleDocumentsPublic);

export type DocsReadRuleDocumentData = {
    slug: string;
};

export type DocsReadRuleDocumentResponse = (RuleDocumentPublic);

export type InventoryReadProcessingUnitsResponse = (MasterUnitsPublic);

export type InventoryCreateProcessingUnitData = {
    requestBody: MasterUnitCreate;
};

export type InventoryCreateProcessingUnitResponse = (MasterUnitPublic);

export type InventoryUpdateProcessingUnitData = {
    requestBody: MasterUnitUpdate;
    unitId: string;
};

export type InventoryUpdateProcessingUnitResponse = (MasterUnitPublic);

export type InventoryReadReceivingUnitsResponse = (MasterUnitsPublic);

export type InventoryCreateReceivingUnitData = {
    requestBody: MasterUnitCreate;
};

export type InventoryCreateReceivingUnitResponse = (MasterUnitPublic);

export type InventoryUpdateReceivingUnitData = {
    requestBody: MasterUnitUpdate;
    unitId: string;
};

export type InventoryUpdateReceivingUnitResponse = (MasterUnitPublic);

export type InventoryCreateInventoryDocumentData = {
    requestBody: InventoryDocumentCreate;
};

export type InventoryCreateInventoryDocumentResponse = (InventoryDocumentPublic);

export type InventoryReadInventoryDocumentsData = {
    businessDateFrom?: (string | null);
    businessDateTo?: (string | null);
    documentNumber?: (string | null);
    documentType?: (InventoryDocumentType | null);
    includeDeleted?: boolean;
    processingUnitId?: (string | null);
    receivingUnitId?: (string | null);
};

export type InventoryReadInventoryDocumentsResponse = (InventoryDocumentsPublic);

export type InventoryReadInventoryDocumentData = {
    documentId: string;
};

export type InventoryReadInventoryDocumentResponse = (InventoryDocumentPublic);

export type InventoryUpdateInventoryDocumentData = {
    documentId: string;
    requestBody: InventoryDocumentCreate;
};

export type InventoryUpdateInventoryDocumentResponse = (InventoryDocumentPublic);

export type InventoryDeleteInventoryDocumentData = {
    documentId: string;
};

export type InventoryDeleteInventoryDocumentResponse = ({
    [key: string]: (string);
});

export type InventoryRestoreInventoryDocumentData = {
    documentId: string;
};

export type InventoryRestoreInventoryDocumentResponse = ({
    [key: string]: (string);
});

export type InventoryReadRawBalancesData = {
    itemName?: (string | null);
    processingUnitId?: (string | null);
};

export type InventoryReadRawBalancesResponse = (InventoryBalancesPublic);

export type InventoryReadFinishedBalancesData = {
    itemName?: (string | null);
    processingUnitId?: (string | null);
};

export type InventoryReadFinishedBalancesResponse = (InventoryBalancesPublic);

export type InventoryReadInventoryLedgerData = {
    colorCode?: (string | null);
    dyeLotNo?: (string | null);
    itemCode?: (string | null);
    itemName: string;
    ledgerKind: InventoryLedgerKind;
    processingUnitId: string;
    woolContent: string;
};

export type InventoryReadInventoryLedgerResponse = (InventoryLedgerEntriesPublic);

export type InventoryReadInventorySuggestionsData = {
    field: string;
    ledgerKind: InventoryLedgerKind;
    query?: (string | null);
};

export type InventoryReadInventorySuggestionsResponse = (InventorySuggestionsPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type ModulesModulesHealthCheckResponse = ({
    [key: string]: (string);
});

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);