"""add inventory tables

Revision ID: 9d7ba96f52cd
Revises: fe56fa70289e
Create Date: 2026-07-13 23:25:42.210921

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d7ba96f52cd'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_import_batch',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('raw_workbook_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('finished_workbook_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('importer_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('reconciliation_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_fingerprint')
    )
    op.create_table('processing_unit',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('receiving_unit',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('inventory_document',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('RAW_RECEIPT', 'RAW_RETURN', 'FINISHED_SHIPMENT', 'FINISHED_RECEIPT', name='inventory_document_type'), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('processing_unit_id', sa.Uuid(), nullable=False),
    sa.Column('receiving_unit_id', sa.Uuid(), nullable=True),
    sa.Column('document_number', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_legacy', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(document_type = 'FINISHED_SHIPMENT' AND receiving_unit_id IS NOT NULL) OR (document_type <> 'FINISHED_SHIPMENT' AND receiving_unit_id IS NULL)", name='ck_inventory_document_receiving_unit'),
    sa.CheckConstraint("is_legacy OR (document_number IS NOT NULL AND btrim(document_number) <> '')", name='ck_inventory_document_number'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processing_unit_id'], ['processing_unit.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receiving_unit_id'], ['receiving_unit.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_document_processing_date', 'inventory_document', ['processing_unit_id', 'business_date'], unique=False)
    op.create_index('ix_inventory_document_type_date', 'inventory_document', ['document_type', 'business_date'], unique=False)
    op.create_index('uq_inventory_document_live_number', 'inventory_document', ['document_type', 'document_number'], unique=True, postgresql_where=sa.text('is_legacy = false'))
    op.create_table('legacy_import_row',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_batch_id', sa.Uuid(), nullable=False),
    sa.Column('workbook_kind', sa.Enum('RAW', 'FINISHED', name='legacy_workbook_kind'), nullable=False),
    sa.Column('workbook_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('worksheet_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_cells', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_balance_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_cleanup', sa.Boolean(), nullable=False),
    sa.CheckConstraint('source_row_number > 0', name='ck_legacy_import_row_number'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['inventory_import_batch.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_batch_id', 'workbook_kind', 'worksheet_name', 'source_row_number')
    )
    op.create_table('inventory_document_line',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('wool_content', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('color_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('dye_lot_no', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('quantity_rolls', sa.Integer(), nullable=False),
    sa.Column('quantity_meters', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.CheckConstraint('line_no > 0', name='ck_inventory_document_line_number'),
    sa.CheckConstraint('quantity_meters IS NULL OR quantity_meters > 0', name='ck_inventory_document_line_meters'),
    sa.CheckConstraint('quantity_rolls >= 0', name='ck_inventory_document_line_rolls'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['inventory_document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'line_no')
    )
    op.create_table('inventory_ledger_entry',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ledger_kind', sa.Enum('RAW', 'FINISHED', name='inventory_ledger_kind'), nullable=False),
    sa.Column('movement_type', sa.Enum('RAW_RECEIPT', 'RAW_RETURN', 'FINISHED_RECEIPT', 'FINISHED_SHIPMENT', 'MIGRATION_RECONCILIATION_OPENING', name='inventory_movement_type'), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('processing_unit_id', sa.Uuid(), nullable=False),
    sa.Column('document_line_id', sa.Uuid(), nullable=True),
    sa.Column('legacy_import_row_id', sa.Uuid(), nullable=True),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('wool_content', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('color_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('dye_lot_no', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('rolls_delta', sa.Integer(), nullable=False),
    sa.Column('meters_delta', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint("(movement_type = 'MIGRATION_RECONCILIATION_OPENING' AND document_line_id IS NULL AND import_batch_id IS NOT NULL) OR (movement_type <> 'MIGRATION_RECONCILIATION_OPENING' AND document_line_id IS NOT NULL)", name='ck_inventory_ledger_entry_source'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_line_id'], ['inventory_document_line.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['inventory_import_batch.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['legacy_import_row_id'], ['legacy_import_row.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processing_unit_id'], ['processing_unit.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_line_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_ledger_entry')
    op.drop_table('inventory_document_line')
    op.drop_table('legacy_import_row')
    op.drop_index('ix_inventory_document_type_date', table_name='inventory_document')
    op.drop_index('ix_inventory_document_processing_date', table_name='inventory_document')
    op.drop_index('uq_inventory_document_live_number', table_name='inventory_document')
    op.drop_table('inventory_document')
    op.drop_table('receiving_unit')
    op.drop_table('processing_unit')
    op.drop_table('inventory_import_batch')
    # ### end Alembic commands ###
