/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRulesRouteImport } from './routes/_layout/rules'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutInventoryShipmentsRouteImport } from './routes/_layout/inventory/shipments'
import { Route as LayoutInventoryRawRouteImport } from './routes/_layout/inventory/raw'
import { Route as LayoutInventoryMastersRouteImport } from './routes/_layout/inventory/masters'
import { Route as LayoutInventoryBalancesRouteImport } from './routes/_layout/inventory/balances'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRulesRoute = LayoutRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInventoryShipmentsRoute =
  LayoutInventoryShipmentsRouteImport.update({
    id: '/inventory/shipments',
    path: '/inventory/shipments',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInventoryRawRoute = LayoutInventoryRawRouteImport.update({
  id: '/inventory/raw',
  path: '/inventory/raw',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInventoryMastersRoute = LayoutInventoryMastersRouteImport.update({
  id: '/inventory/masters',
  path: '/inventory/masters',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInventoryBalancesRoute = LayoutInventoryBalancesRouteImport.update({
  id: '/inventory/balances',
  path: '/inventory/balances',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/rules': typeof LayoutRulesRoute
  '/settings': typeof LayoutSettingsRoute
  '/inventory/balances': typeof LayoutInventoryBalancesRoute
  '/inventory/masters': typeof LayoutInventoryMastersRoute
  '/inventory/raw': typeof LayoutInventoryRawRoute
  '/inventory/shipments': typeof LayoutInventoryShipmentsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/rules': typeof LayoutRulesRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/inventory/balances': typeof LayoutInventoryBalancesRoute
  '/inventory/masters': typeof LayoutInventoryMastersRoute
  '/inventory/raw': typeof LayoutInventoryRawRoute
  '/inventory/shipments': typeof LayoutInventoryShipmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/rules': typeof LayoutRulesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/inventory/balances': typeof LayoutInventoryBalancesRoute
  '/_layout/inventory/masters': typeof LayoutInventoryMastersRoute
  '/_layout/inventory/raw': typeof LayoutInventoryRawRoute
  '/_layout/inventory/shipments': typeof LayoutInventoryShipmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/rules'
    | '/settings'
    | '/inventory/balances'
    | '/inventory/masters'
    | '/inventory/raw'
    | '/inventory/shipments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/rules'
    | '/settings'
    | '/'
    | '/inventory/balances'
    | '/inventory/masters'
    | '/inventory/raw'
    | '/inventory/shipments'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/rules'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/inventory/balances'
    | '/_layout/inventory/masters'
    | '/_layout/inventory/raw'
    | '/_layout/inventory/shipments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rules': {
      id: '/_layout/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof LayoutRulesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/shipments': {
      id: '/_layout/inventory/shipments'
      path: '/inventory/shipments'
      fullPath: '/inventory/shipments'
      preLoaderRoute: typeof LayoutInventoryShipmentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/raw': {
      id: '/_layout/inventory/raw'
      path: '/inventory/raw'
      fullPath: '/inventory/raw'
      preLoaderRoute: typeof LayoutInventoryRawRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/masters': {
      id: '/_layout/inventory/masters'
      path: '/inventory/masters'
      fullPath: '/inventory/masters'
      preLoaderRoute: typeof LayoutInventoryMastersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/balances': {
      id: '/_layout/inventory/balances'
      path: '/inventory/balances'
      fullPath: '/inventory/balances'
      preLoaderRoute: typeof LayoutInventoryBalancesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutRulesRoute: typeof LayoutRulesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutInventoryBalancesRoute: typeof LayoutInventoryBalancesRoute
  LayoutInventoryMastersRoute: typeof LayoutInventoryMastersRoute
  LayoutInventoryRawRoute: typeof LayoutInventoryRawRoute
  LayoutInventoryShipmentsRoute: typeof LayoutInventoryShipmentsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutRulesRoute: LayoutRulesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutInventoryBalancesRoute: LayoutInventoryBalancesRoute,
  LayoutInventoryMastersRoute: LayoutInventoryMastersRoute,
  LayoutInventoryRawRoute: LayoutInventoryRawRoute,
  LayoutInventoryShipmentsRoute: LayoutInventoryShipmentsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
